[workspace]
members = ["packages/primitives/*/*"]
resolver = "2"

[workspace.package]
authors = ["Nixy <info@nixy.software>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/NixySoftware/radix"
version = "0.1.0"

[workspace.dependencies]
leptos = { version = "0.6.9", features = ["nightly"] }
log = "0.4.21"
# wasm-bindgen = "0.2.92"
