[package]
name = "radix-leptos-dismissable-layer"
description = "Leptos port of Radix Dismissable Layer."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
