[package]
name = "radix-leptos-menu"
description = "Leptos port of Radix Menu."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
radix-leptos-direction = { path = "../direction", version = "0.0.1" }
radix-leptos-popper = { path = "../popper", version = "0.0.1" }
