[package]
name = "radix-leptos-collection"
description = "Leptos port of Radix Collection."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
radix-leptos-compose-refs = { path = "../compose-refs", version = "0.0.1" }
radix-leptos-primitive = { path = "../primitive", version = "0.0.1" }
