[package]
name = "radix-number"
description = "Rust port of Radix Core Number."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
